name: camera_with_gps_example
description: Demonstrates how to use camera_with_gps.
version: 1.2.0
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  camera_with_gps:
    path: ../
  permission_handler: ^11.0.0
flutter:
  uses-material-design: true
